
version: '3.8'
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    volumes:
      - ./server/config.ini:/config.ini
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=NOMBRE1
      - APELLIDO=APELLIDO1
      - DOCUMENTO=DOCUMENTO1
      - NACIMIENTO=1111-10-10
      - NUMERO=1111
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-1.csv:/agency-1.csv
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
